// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkgbogpytkwpdgwywrrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrZ2JvZ3B5dGt3cGRnd3l3cnJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4ODg1MzUsImV4cCI6MjA2OTQ2NDUzNX0.OvudPckoECoeau-DudtRjk6mqHb4md76rRY0jv3c4BE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});